use_blueprint:
  path: nfc_playlist_switch_blueprint.yaml
  input:
    playlist_name: "New Year Playlist 1"
    tag_id: "04-B9-15-AF-7A-26-81"
    spotify_uri: "spotify:playlist:3XXQEDPWBEKjgSpAJur8YP"
    device_1_account: "01KACG05YGPRDMAJDPE29KDBKV"
    device_1_media_player: "media_player.stue_1140714430_spotcast"
    base_playlist_helper: "input_text.base_playlist_uri"
