alias: Kitchen Speaker - Hard Reset via Admin NFC Card
description: >-
  Admin-only: Resets kitchen speaker by power cycling the Hue smart plug when
  admin NFC card is scanned
triggers:
  - event_type: tag_scanned
    event_data:
      tag_id: 04-42-FB-AE-7A-26-81
    trigger: event
actions:
  # Play master sound
  - delay:
      milliseconds: 300
  - service: button.press
    target:
      entity_id: button.nfc_party_controller_2_play_master

  # Wait for master sound to finish (roughly)
  - delay:
      milliseconds: 2000

  - action: light.turn_off
    target:
      entity_id:
        - light.smart_plug
    data: {}
  - delay:
      seconds: 10
  - action: light.turn_on
    target:
      entity_id:
        - light.smart_plug
    data: {}
mode: single
